services:
  django:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres  # Bu yerga postgres servisini qo'shing
    env_file:
      - .env
    restart: always

  redis:
    image: redis:latest
    restart: always

  celery:
    build: .
    command: celery -A config worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
      - django
    env_file:
      - .env
    restart: always

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
      - django
    env_file:
      - .env
    restart: always

  postgres:
    image: postgres:latest 
    environment:
      POSTGRES_DB: tester_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Azizbek1410
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:

