# Generated by Django 5.2.1 on 2025-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
