# Generated by Django 5.2.1 on 2025-05-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_category_alter_test_options_question_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_persentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coins_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
