# Generated by Django 5.2.1 on 2025-05-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_option_1_question_option_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_first_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
