# Generated by Django 5.2.1 on 2025-05-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_testresult_is_first_attempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='score_persentage',
            new_name='score_percentage',
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.category'),
        ),
    ]
